### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by 3xpl0rer** [guillaC/BatchObfuscator#4]
How to obfuscate, when the code got put in ???

**Comment by guillaC** [comment]
Hello,

- First, select the part of the code (or all the code).
- Right-click, and you will have access to obfuscation features.
- You can obfuscate all or parts of the code, using different obfuscation methods or not.

**Comment by guillaC** [comment]
@3xpl0rer,
I just added a Usage section to the README. Is that okay with you ?
